spring:
  devtools:
    restart:
      enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/watch?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: 257925
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,slf4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  redis:
    database: 0
    host: localhost
    port: 6379
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
  thymeleaf:
    cache: false
    check-template: true
    check-template-location: true
    encoding: utf-8
    servlet:
      content-type: text/html
    enabled: true
    mode: LEGACYHTML5
    prefix: classpath:/templates/
    suffix: .html

api-prefix: /api

open-prefix: /open

auth-url: http://localhost:8080/oauth/token
wx:
  appid: wx934fa0926849e343
  secret: 8f8c479d7adf56638cdec5536690fd72
server:
  port: 8080
leancloud:
  appid: 3uxiAoexr3S8H99Vm0YlBBoU-gzGzoHsz
  secret: 68E4Kjo8w7lVoMwynry6tKn0
